### ISSUE TITLE
create more tiles when a lot of instances

### ISSUE THREAD

**Issue by bertt** [Geodan/i3dm.export#13]
create more (smaller) tiles when there are lot of instances in a tile (like a quadtree).
Maximum number of instances per tile is a setting.

**Comment by MortezaYaqubkhani** [comment]
Hi,
I just wanted to be a little bit clear. By creating more tilesets, you mean that ultimately each small tileset should consist of one instance? Am I right?
In this case, the number of models (instance models .i3dm files) that we use for different tilesets ( with different sizes) could reduce significantly, since each tileset contains only one instance which can be located in the tileset's center.
One question: If I want to explore more, which part of the code should I focus on? The "program.cs" that deals with defining tilesets and their properties (bounding box)?

**Comment by bertt** [comment]
duplicate of https://github.com/Geodan/i3dm.export/issues/24

closing this issue
